# Generated by Django 5.1.6 on 2025-03-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_choose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
