# Generated by Django 5.1.6 on 2025-03-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_special_festivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family_Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
