# Generated by Django 5.1.6 on 2025-03-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_breakfast'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='data_category',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
