# Generated by Django 5.1.6 on 2025-03-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
