# Generated by Django 5.1.6 on 2025-03-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_rename_image_cartitem_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='image_url',
            new_name='image',
        ),
    ]
