# Generated by Django 5.1.6 on 2025-03-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_cvv',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_expiry',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
