# Generated by Django 5.1.6 on 2025-03-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_alter_payment_card_cvv_alter_payment_card_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
